#!/bin/sh

# Copyright (c) 2016 sitec systems GmbH.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Lesser Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [ -e /usr/lib/python2.7/site-packages/ftk/__main__pyc ]; then
	python /usr/lib/python2.7/site-packages/ftk/__main__.pyc $*
else
	python /usr/lib/python2.7/site-packages/ftk/__main__.py $*
fi
